# Generated by Django 3.0.5 on 2021-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(4, '4'), (6, '6'), (5, '5'), (0, '0'), (2, '2'), (9, '9'), (3, '3'), (1, '1'), (7, '7'), (10, '10'), (8, '8')], default=0),
        ),
    ]
