# Generated by Django 3.0.5 on 2021-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210121_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (3, '3'), (7, '7'), (0, '0'), (8, '8'), (5, '5'), (9, '9'), (10, '10'), (2, '2'), (4, '4'), (6, '6')], default=0),
        ),
    ]
