# Generated by Django 3.0.5 on 2021-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210121_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (8, '8'), (1, '1'), (4, '4'), (10, '10'), (6, '6'), (7, '7'), (2, '2'), (9, '9'), (5, '5'), (3, '3')], default=0),
        ),
    ]
