# Generated by Django 3.0.5 on 2021-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210121_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(to='api.Genre'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (5, '5'), (2, '2'), (8, '8'), (6, '6'), (10, '10'), (4, '4'), (7, '7'), (0, '0'), (9, '9'), (3, '3')], default=0),
        ),
    ]
