# Generated by Django 3.0.5 on 2021-01-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210123_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (3, '3'), (10, '10'), (2, '2'), (7, '7'), (5, '5'), (8, '8'), (4, '4'), (6, '6'), (9, '9'), (0, '0')], default=0),
        ),
    ]
