# Generated by Django 3.0.5 on 2021-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210123_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(2, '2'), (6, '6'), (3, '3'), (7, '7'), (4, '4'), (10, '10'), (8, '8'), (5, '5'), (1, '1'), (0, '0'), (9, '9')], default=0),
        ),
    ]
